#url: https://my.external.domain:port/
class: simple
title: Simple page - Sample Interface

buttons:
  light_hall:
    icon: lamp
    item: unit:light/hall
    title: Hall
  alarm:
    icon: attn
    item: lvar:security/alarm
    title: Alarm
  cctv:
    title: Rec.
    icon: cam
    item: unit:equipment/cctv

cameras:
  hall:
    image: /rpvt?f=127.0.0.1:8118/cam/3?nocache=$NOCACHE

layout:
  camera:
    id: hall
    reload: 1
    action: url:/ui/
  buttons:
    - light_hall
    - alarm
    - cctv
  #sys-block: true
